Support HD Capes
yushijinhun/skinview-utils pull request #15
Opened 2023-01-05 21:14 UTC by james090500

Adds support for HD capes

2023-01-10 15:59 UTC, Hacksore requested changes

2023-01-10 15:59 UTC, Hacksore commented on src/process.ts
> +	} else if ((image.height % (image.width / 2)) == 0) {
Can you please add a comment explaining what this branch is for?

2023-01-10 17:14 UTC, james090500 commented on src/process.ts
> +	} else if ((image.height % (image.width / 2)) == 0) {
I have added requested changes.

2023-01-11 15:13 UTC, Hacksore approved these changes
LGTM but @yushijinhun might have other opinions.

2023-01-11 18:58 UTC, james090500 commented
When moving the code from https://github.com/bs-community/skinview3d/pull/128/ to here I forgot to include a method for loading a specific frame.

2023-01-30 14:14 UTC, james090500 commented
Any update on this?

2023-01-30 14:14 UTC, james090500 commented
Any update on this?

2023-01-30 15:13 UTC, Hacksore commented
@yushijinhun can you please review this?

2024-12-23 13:27 UTC, Hacksore commented
I believe @james090500 ported this into his lib here.

https://github.com/MinecraftCapes/minecraft-skin-viewer

2024-12-23 13:27 UTC, closed without merging